version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: news_paper_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: news_paper_vip
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ko_KR.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - news_paper_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d news_paper_vip" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: news_paper_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - news_paper_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes --requirepass ""

  # API 서버
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news_paper_api
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: news_paper_vip
      DB_USER: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      JWT_SECRET: news_paper_vip_super_secret_key_2024
      JWT_EXPIRE: 7d
      JWT_REFRESH_SECRET: news_paper_vip_refresh_secret_key_2024
      JWT_REFRESH_EXPIRE: 30d
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - news_paper_network
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads

  # pgAdmin (데이터베이스 관리 도구)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: news_paper_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@newspaper-vip.com
      PGADMIN_DEFAULT_PASSWORD: admin123!
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - news_paper_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  news_paper_network:
    driver: bridge
