version: '3.8'

services:
  staging-backend:
    build:
      context: ./server-backend
      dockerfile: Dockerfile
    ports:
      - "50001:50000"
    env_file:
      - ./server-backend/.env.staging
    environment:
      - NODE_ENV=staging
      - PORT=50000
    networks:
      - staging-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  staging-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      staging-backend:
        condition: service_healthy
    networks:
      - staging-network
    restart: unless-stopped
    environment:
      - API_BASE=http://staging-backend:50000

networks:
  staging-network:
    driver: bridge