version: '3.8'

services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: community-mysql-test
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: community_root_password_2024
      MYSQL_DATABASE: community_hub
      MYSQL_USER: community_user
      MYSQL_PASSWORD: community_password_2024
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  # Redis
  redis:
    image: redis:7-alpine
    container_name: community-redis-test
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass community_redis_password_2024
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      timeout: 3s
      retries: 5
