version: '3.8'

services:
  backend:
    build:
      context: ./server-backend
      dockerfile: Dockerfile
    container_name: community-backend-prod-local
    restart: unless-stopped
    env_file:
      - ./server-backend/.env.prod
    ports:
      - "50002:50000"
    networks:
      - community-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - ./logs:/app/logs:rw

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: community-frontend-prod-local
    restart: unless-stopped
    ports:
      - "3002:80"
    networks:
      - community-network
    depends_on:
      backend:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    # read_only: true

  # redis:
  #   image: redis:7-alpine
  #   container_name: community-redis-prod
  #   restart: unless-stopped
  #   command: redis-server --appendonly yes
  #   networks:
  #     - community-network
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"
  #   security_opt:
  #     - no-new-privileges:true
  #   read_only: true
  #   tmpfs:
  #     - /data
  #   volumes:
  #     - redis-data:/data

# volumes:
#   redis-data:
#     driver: local

networks:
  community-network:
    driver: bridge