apiVersion: v2
name: community-platform
description: Community Platform - A comprehensive community management system
type: application
version: 2.0.0
appVersion: "2.0.0"
home: https://github.com/your-org/community-platform
sources:
  - https://github.com/your-org/community-platform
maintainers:
  - name: Community Platform Team
    email: team@community.example.com
keywords:
  - community
  - social
  - platform
  - microservices
  - kubernetes
dependencies:
  - name: postgresql
    version: 12.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: mongodb
    version: 13.6.0
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: 17.3.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: elasticsearch
    version: 19.5.0
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
  - name: prometheus
    version: 25.8.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: 6.50.7
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
  - name: jaeger
    version: 0.69.0
    repository: https://jaegertracing.github.io/helm-charts
    condition: jaeger.enabled
