apiVersion: v1
kind: Namespace
metadata:
  name: community-platform
  labels:
    name: community-platform
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/version: "2.0.0"
    app.kubernetes.io/component: platform
    app.kubernetes.io/part-of: community-ecosystem
