# API Gateway Service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: admin
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: api-gateway

---
# Auth Service
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: auth-service

---
# User Service
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: user-service
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: user-service

---
# Content Service
apiVersion: v1
kind: Service
metadata:
  name: content-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: content-service
spec:
  type: ClusterIP
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: content-service

---
# Notification Service
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: notification-service
spec:
  type: ClusterIP
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: notification-service

---
# Analytics Service
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: analytics-service
spec:
  type: ClusterIP
  ports:
  - port: 3005
    targetPort: 3005
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: analytics-service

---
# Search Service
apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: search-service
spec:
  type: ClusterIP
  ports:
  - port: 3006
    targetPort: 3006
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: search-service

---
# File Service
apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: file-service
spec:
  type: ClusterIP
  ports:
  - port: 3007
    targetPort: 3007
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: file-service

---
# Chat Service
apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: chat-service
spec:
  type: ClusterIP
  ports:
  - port: 3008
    targetPort: 3008
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: chat-service

---
# Admin Service
apiVersion: v1
kind: Service
metadata:
  name: admin-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: admin-service
spec:
  type: ClusterIP
  ports:
  - port: 3009
    targetPort: 3009
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: admin-service

---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: frontend

---
# Database Services
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: redis

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: search
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: 9200
    protocol: TCP
    name: http
  - port: 9300
    targetPort: 9300
    protocol: TCP
    name: transport
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: elasticsearch

---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: analytics
spec:
  type: ClusterIP
  ports:
  - port: 8123
    targetPort: 8123
    protocol: TCP
    name: http
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: native
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: clickhouse

---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9001
    targetPort: 9001
    protocol: TCP
    name: console
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: minio

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: kafka

---
# Monitoring Services
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: prometheus

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: monitoring
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: grafana

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: community-platform
  labels:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 16686
    targetPort: 16686
    protocol: TCP
    name: http
  - port: 14268
    targetPort: 14268
    protocol: TCP
    name: jaeger
  selector:
    app.kubernetes.io/name: community-platform
    app.kubernetes.io/component: jaeger
