filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/community/*.log
  fields:
    service: community-backend
  fields_under_root: true
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after

- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
  fields:
    service: nginx
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/mysql/*.log
  fields:
    service: mysql
  fields_under_root: true

- type: log
  enabled: true
  paths:
    - /var/log/redis/*.log
  fields:
    service: redis
  fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
