# Velero Backup Schedule for Community Platform
# Version: 2.0.0

apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: community-platform-daily
  namespace: velero
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  template:
    includedNamespaces:
    - community-platform
    - monitoring
    - logging
    storageLocation: default
    volumeSnapshotLocations:
    - default
    ttl: 720h  # 30 days
    hooks:
      resources:
      - name: pre-backup-hook
        includedNamespaces:
        - community-platform
        labelSelector:
          matchLabels:
            app: postgres
        pre:
        - exec:
            container: postgres
            command:
            - /bin/bash
            - -c
            - "pg_dump -U community_user -d community_production > /tmp/backup.sql"
        - exec:
            container: postgres
            command:
            - /bin/bash
            - -c
            - "pg_dump -U community_user -d community_analytics > /tmp/analytics_backup.sql"

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: community-platform-weekly
  namespace: velero
spec:
  schedule: "0 1 * * 0"  # Weekly on Sunday at 1 AM
  template:
    includedNamespaces:
    - community-platform
    - monitoring
    - logging
    storageLocation: default
    volumeSnapshotLocations:
    - default
    ttl: 2160h  # 90 days
    hooks:
      resources:
      - name: pre-backup-hook
        includedNamespaces:
        - community-platform
        labelSelector:
          matchLabels:
            app: postgres
        pre:
        - exec:
            container: postgres
            command:
            - /bin/bash
            - -c
            - "pg_dump -U community_user -d community_production > /tmp/backup.sql"
        - exec:
            container: postgres
            command:
            - /bin/bash
            - -c
            - "pg_dump -U community_user -d community_analytics > /tmp/analytics_backup.sql"

---
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: community-platform-monthly
  namespace: velero
spec:
  schedule: "0 0 1 * *"  # Monthly on the 1st at midnight
  template:
    includedNamespaces:
    - community-platform
    - monitoring
    - logging
    storageLocation: default
    volumeSnapshotLocations:
    - default
    ttl: 8760h  # 1 year
    hooks:
      resources:
      - name: pre-backup-hook
        includedNamespaces:
        - community-platform
        labelSelector:
          matchLabels:
            app: postgres
        pre:
        - exec:
            container: postgres
            command:
            - /bin/bash
            - -c
            - "pg_dump -U community_user -d community_production > /tmp/backup.sql"
        - exec:
            container: postgres
            command:
            - /bin/bash
            - -c
            - "pg_dump -U community_user -d community_analytics > /tmp/analytics_backup.sql"
