name: Contrast Audit

on:
  pull_request: {}
  push:
    branches:
      - main
      - master

jobs:
  contrast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: |
          cd server-backend
          npm install
      - name: Run contrast audit
        run: |
          cd server-backend
          npm run test:contrast
      - name: Upload contrast report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: contrast-report
          path: server-backend/contrast-report.json
